# https://kind-jepsen-127abc.netlify.com/

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads"

# Netlify CMS access definitions
collections: 
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Site data"
        name: "site-data"
        file: "_data/site-data.yml"  
        fields: 
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "Footer address"
            name: "address"
            widget: "object"
            fields:
              - label: "Author"
                name: "author"
                widget: "string"
              - label: "Street Address"
                name: "street-address"
                widget: "string"
              - label: "City, State"
                name: "localily"
                widget: "string"
              - label: "Country"
                name: "country"
                widget: "string"
            - label: "Footer Contact Data"
              name: "contact-data"
              widget: "object"
              fields:
                - label: "Short phone number"
                  name: "display-phone"
                  widget: "string"
                - label: "Full phone number"
                  name: "url-phone"
                  widget: "string"
                - label: "Web Address"
                  name: "web"
                  widget: "string"
  - label: "About Page settings"
    name: "about-data"
    files:
      - label: "About Page data"
        name: "about-data"
        file: "_data/about-data.yml"
        fields: 
          - label: "About page data"
            name: "about"
            widget: "markdown"
          - label: "Address"
            name: "address"
            widget: "string"