backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads"

# Netlify CMS access definitions
collections: 
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "SEO"
        name: "seo"
        file: "_data/site-data.yml"  
        fields: 
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
      - label: "About Page"
        name: "about-page"
        file: "_data/site-data.yml"  
        fields: 
          - label: "About page content"
            name: "about-data"
            widget: "string"
       - label: "Footer Page"
        name: "footer-data"
        file: "_data/site-data.yml"  
        fields: 
          - label: "Address"
            name: "address"
            widget: "string"
        