backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads"

# Netlify CMS access definitions
collections: 
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Site data"
        name: "site-data"
        file: "_data/site-data.yml"  
        fields: 
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "About page data"
            name: "about"
            widget: "markdown"
          - label: "Address"
            name: "address"
            widget: "string"